### ISSUE TITLE
render  v-model

### ISSUE THREAD

**Issue by Bright0810** [vincentSea/vue-free-table#1]
使用 render渲染的时候 input 无法使用v-model

**Comment by scarecrowdu** [comment]
官网有说明：渲染函数中没有与 v-model 的直接对应——你必须自己实现相应的逻辑
https://cn.vuejs.org/v2/guide/render-function.html#v-model

**Comment by scarecrowdu** [comment]
已经新增input的v-model案例

**Comment by Bright0810** [comment]
> 已经新增input的v-model案例

十分感谢
